// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcUKOoNqRx4Y4T-oY4BiLhy81xckeiDQo',
    appId: '1:796311176657:web:a5226f0a961db9619a0cf0',
    messagingSenderId: '796311176657',
    projectId: 'elira-1aac7',
    authDomain: 'elira-1aac7.firebaseapp.com',
    storageBucket: 'elira-1aac7.firebasestorage.app',
    measurementId: 'G-TJCS5W5YT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCTuBQBzNpUd7eKtFnDd3iU33ptGX5Jow',
    appId: '1:796311176657:android:4302b49333854b709a0cf0',
    messagingSenderId: '796311176657',
    projectId: 'elira-1aac7',
    storageBucket: 'elira-1aac7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7YfkxH7UVEUYfXEM8SB8HN5OD8lsQhTw',
    appId: '1:796311176657:ios:7ec6c28264588e189a0cf0',
    messagingSenderId: '796311176657',
    projectId: 'elira-1aac7',
    storageBucket: 'elira-1aac7.firebasestorage.app',
    iosBundleId: 'com.barkha.elira',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7YfkxH7UVEUYfXEM8SB8HN5OD8lsQhTw',
    appId: '1:796311176657:ios:dcbd0cbe3966a7ae9a0cf0',
    messagingSenderId: '796311176657',
    projectId: 'elira-1aac7',
    storageBucket: 'elira-1aac7.firebasestorage.app',
    iosBundleId: 'com.example.elira',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcUKOoNqRx4Y4T-oY4BiLhy81xckeiDQo',
    appId: '1:796311176657:web:603fdb42d36942d99a0cf0',
    messagingSenderId: '796311176657',
    projectId: 'elira-1aac7',
    authDomain: 'elira-1aac7.firebaseapp.com',
    storageBucket: 'elira-1aac7.firebasestorage.app',
    measurementId: 'G-ZJZPF4613W',
  );
}
